[package]
name = "bibtl"
version = "0.1.0"
edition = "2024"

[dependencies]
biblatex = "0.11.0"
clap = { version = "4.5.60", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.0"
